version: '3'
services:
    nginx:
        build: nginx/
        ports:
            - '80:80'
            - '443:443'
        volumes:
            - '/var/www/_letsencrypt:/var/www/_letsencrypt'
            - '/etc/nginx/sites-available:/etc/nginx/sites-available'
            - '/etc/nginx/sites-enabled:/etc/nginx/sites-enabled'
            - '/etc/letsencrypt:/etc/letsencrypt'
    node:
        build: node/
        ports:
            - '3300:3300'
        volumes:
            - '/var/www/_letsencrypt:/var/www/_letsencrypt'
            - '/var/run/docker.sock:/var/run/docker.sock'
            - '/etc/nginx/sites-available:/etc/nginx/sites-available'
            - '/etc/nginx/sites-enabled:/etc/nginx/sites-enabled'
            - '/etc/letsencrypt:/etc/letsencrypt'
